title: "Kyros Studio"
description: "Portfolio de photographie et services de Kyros."
baseurl: "/kyros" # Si ton dépôt s'appelle "kyros". Laisse vide si tu veux que le site soit à la racine.
url: "https://kyroswall.github.io" # L'URL de ton site GitHub Pages

# Thème
theme: raviriley/agency-jekyll-theme

# Informations sur l'auteur
author:
  name: "Kyros"
  email: "tonemail@example.com"

# Social media settings
social:
  twitter: "https://twitter.com/toncompte"
  linkedin: "https://linkedin.com/in/toncompte"
  github: "https://github.com/toncompte"

# Autres options de configuration
plugins:
  - jekyll-feed
